language: csharp
solution: BradlBot.sln
mono: none
dotnet: 1.0.3
dist: trusty
install:
 - dotnet restore
script:
 - dotnet build -c Release
 - cd BradlBot
 - dotnet run -c Release -addonsfolder
 - cd ..
 - cp BaseCommands/bin/Release/netstandard1.4/BaseCommands.dll BradlBot/addons
