language: csharp
solution: BradlBot.sln
mono: none
dotnet: 2.2
dist: xenial
install:
 - dotnet restore
script:
 - dotnet build -c Release
 - cd BradlBot
 - dotnet run -c Release -addonsfolder
 - cd ..
 - cp BaseCommands/bin/Release/netstandard2.0/BaseCommands.dll BradlBot/addons
